eu_countries_codes = ["AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE"]

eu_countries_codes_details = {
    "AT": "Austria",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GR": "Greece",
    "HU": "Hungary",
    "IE": "Ireland",
    "IT": "Italy",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MT": "Malta",
    "NL": "Netherlands",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ES": "Spain",
    "SE": "Sweden"
}

eu_countries_codes_VAT_rate_high = {
    "BE": 21,
    "FR": 20,
    "AT": 20,
    "BG": 20,
    "IT": 22,
    "PL": 23,
    "CZ": 21,
    "PT": 23,
    "DK": 25,
    "LV": 21,
    "RO": 19,
    "DE": 19,
    "LT": 21,
    "SI": 22,
    "EE": 20,
    "LU": 17,
    "SK": 20,
    "IE": 23,
    "HU": 27,
    "FI": 24,
    "EL": 24,
    "SE": 25,
    "ES": 21,
    "NL": 21,
    "MT": 18,
    "CY": 19
}